baseURL = "https://zcc.rs/"
languageCode = "zh-cn"
title = "Blog"
theme = "github-style"

[taxonomies]
  author = "authors"
  category = "categories"
  series = "series"
  tag = "tags"

[outputs]
  home = ["HTML"]

[params]
  author = "JiDe"
  description = "..."
  github = "zccrs"
  twitter = "zccrs"
  email = "zccrs@live.com"
  url = "https://zcc.rs/"
  keywords = "blog, google analytics"
  lastmod = true
  favicon = "/images/avatar.png"
  location = "China"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = true

[[params.links]]
  title = "justforlxz"
  href = "https://blog.justforlxz.com/"
  icon = "https://blog.justforlxz.com/img/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[params.gitalk]
  repo = "blog" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
  owner = "zccrs" # æ‚¨çš„GitHub ID
  admin = "zccrs" # æ‚¨çš„GitHub ID
  id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
  title = "document.title"
  labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
  perPage = 30 # Pagination size, with maximum 100.
  pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
  createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
  distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
  proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
  language = "[en, zh-CN, zh-TW]"
